vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        pdf:
            uri_prefix: pdfs
            upload_destination: '%kernel.project_dir%/public/pdfs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        video:
            uri_prefix: videos
            upload_destination: '%kernel.project_dir%/public/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer